steps:
- name: 'gcr.io/cloud-builders/gcloud' 
  entrypoint: 'bash' 
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1800 && gcloud app deploy app.yaml']
options:
  logging: CLOUD_LOGGING_ONLY
  env: ['RAILS_MASTER_KEY=$_RAILS_MASTER_KEY']
timeout: 1200s